apiVersion: v1
kind: Service
metadata:
  name: mindspace-backend
  namespace: mindspace
spec:
  selector:
    app: mindspace-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP