apiVersion: v1
kind: Service
metadata:
  name: mindspace-frontend
  namespace: mindspace
spec:
  selector:
    app: mindspace-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP