apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindspace-ingress
  namespace: mindspace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mindspace.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mindspace-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mindspace-backend
                port:
                  number: 5000