apiVersion: v1
kind: Service
metadata:
  name: mindspace-postgres
  namespace: mindspace
spec:
  selector:
    app: mindspace-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP